### ISSUE TITLE
Context.__getattr__ should rise AttributeError instead of KeyError

### ISSUE THREAD

**Issue by gtors** [dry-python/stories#222] opened 2019-09-03 12:43 UTC
According to the Python documentation:

```
 object.__getattr__(self, name)

    Called when the default attribute access fails with an AttributeError (either __getattribute__() raises an AttributeError because name is not an instance attribute or an attribute in the class tree for self; or __get__() of a name property raises AttributeError). This method should either return the (computed) attribute value or raise an AttributeError exception.
```

**Comment by proofit404** [comment] 2019-09-03 12:53
Hi! Thank you for giving the dry-python project a try :tada: 

I completely agree with you. This inconsistent behavior was introduced from the start of the project. So I don't think too much about it at the beginning.

We'll fix it in the next release.

I still not sure will it be `AttributeError` or `ContextError` with a useful message about current state available.

Best regards,
Artem.

Duplicate of #16

**Closed by proofit404** 2019-09-03 12:53 UTC

**Comment by gtors** [comment] 2019-09-03 13:07
This bug breaks a follow code:

```
hasattr(ctx, "someattr")
```

`ctx` is an object, so I think `hasattr` should be legal operation on it.

**Comment by proofit404** [comment] 2019-09-03 13:26
Yes, let's make it `AttributeError` so.

But I don't think that using hasattr in the story steps is a good idea.

Hopefully, we have strict linter for this.
