### ISSUE TITLE
[RFC] Context in SuccessSummary

### ISSUE THREAD

**Issue by chkoar** [dry-python/stories#380] opened 2020-05-11 08:46 UTC
Hi, maybe that's a dumb question but is there a specific reason that the context in not getting attached in the `SuccessSummary`?

**Comment by proofit404** [comment] 2020-05-11 08:59
Hi! Thank you for the feedback!

It looks like a duplicate of https://github.com/dry-python/stories/issues/352

Best regards,
Artem.

**Closed by proofit404** 2020-05-11 08:59 UTC
